version: "3.7"

services:
  notifications-database-test:
    image: postgres:13
    restart: always
    networks:
      - notifications-ms-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DevOps-Notifications-test
    healthcheck:
      test: pg_isready -U postgres -d DevOps-Notifications-test
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 5432

  notifications-server-test:
    build:
      dockerfile: Dockerfile.test
      context: .
    networks:
      - notifications-ms-test
      - network-for-ms
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: notifications-database-test
      DATABASE_SCHEMA: DevOps-Notifications-test
      DATABASE_PORT: 5432
      SERVER_PORT: 9095
      AMQP_SERVER_URL: amqp://guest:guest@rabbitmq:5673/
      EVENTS_MS: http://localhost:9081/events
    ports:
      - 9095
    depends_on:
      notifications-database-test:
        condition: service_healthy

  database-events-test:
    image: postgres:13
    restart: always
    networks:
      - events-ms
      - network-for-ms
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SystemEvents-test
    healthcheck:
      test: pg_isready -U postgres -d SystemEvents-test
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "5451:5432"

  events-server:
    build:
      context: 'https://github.com/DevOps-Tim9/events-ms.git#develop'
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - events-ms
      - network-for-ms
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: database-events-test
      DATABASE_SCHEMA: SystemEvents-test
      DATABASE_PORT: 5432
      SERVER_PORT: 9081
    ports:
      - "9081:9081"
    depends_on:
      database-events-test:
        condition: service_healthy

networks:
  events-ms:
    name: events-ms
    driver: bridge
  notifications-ms-test:
    name: notifications-ms-test
    driver: bridge
  network-for-ms:
    name: network-for-ms
